[package]
name = "prime-finder-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reedline = "0.16.0"
serde = "1.0.152"
toml = "0.7.2"
